name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      # Setup key
      - run: set -eu 
      - run: mkdir "$HOME/.ssh"
      - run: echo "${{ secrets.BEGETSECRET }}" > "$HOME/.ssh/key"
      - run: chmod 600 "$HOME/.ssh/key"
      # Deploy
      - run: cd .output/public && rsync -e "ssh -p 22 -i $HOME/.ssh/key -o StrictHostKeyChecking=no" --archive --compress --delete . root@5.35.86.224:/var/www/renderroom/data/www/renderroom